apiVersion: v1
kind: Pod
metadata:
    name: nginx-config-map
    labels:
        app: nginx
spec:
    volumes:
        - name: pod-config-map
          configMap:
            name: volume-mounts-config-map
    containers:
        - name: nginx
          image: nginx
          volumeMounts:
              - name: pod-config-map
                mountPath: /usr/share/nginx/html