apiVersion: v1
kind: Pod
metadata:
    name: nginx-change-config
    labels:
        app: nginx
spec:
    volumes:
        - name: new-nginx-config
          hostPath:
            path: /data/newconfig 
    containers:
        - name: nginx
          image: nginx
          volumeMounts:
              - name: new-nginx-config
                mountPath: /etc/nginx/conf.d