apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
        name: nodeport
spec:
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30085
    sessionAffinity: ClientIP
    selector:
        app: test