apiVersion: v1
kind: Pod
metadata:
    name: nginx-env-config-map
    labels:
        app: nginx
spec:
    containers:
        - name: nginx
          image: nginx
          envFrom:
              - configMapRef:
                  name: env-config-map