apiVersion: v1
kind: Pod
metadata:
    name: nginx-config-map
    labels:
        app: nginx
spec:
    volumes:
        - name: pod-config-map
          configMap:
            name: multi-value-config-map
            items:
                - key: "index.html"
                  path: "index.html"
                - key: "default.conf"
                  path: "default.conf"
    containers:
        - name: nginx
          image: nginx
          volumeMounts:
              - name: pod-config-map
                mountPath: /usr/share/nginx/html